# ANN - Artifical Neural Network

In [48]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

inputs = np.arange(1, 100, 1, dtype=np.uint8)
labels = inputs 

In [49]:
from sympy import *

x = Symbol('x')
y= x**2

yprime = y.diff(x)
display(yprime, y)

f = lambdify(x, yprime, 'numpy')
labels = f(inputs)

labels


2*x

x**2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198], dtype=uint8)

In [95]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        display(self.weights.shape)
        self.biases = np.zeros((1,n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

inputs = inputs.reshape(99,1) #wow ok so apparently this operation does not act on the object...not a persistent change, one must reassign to an l-value
inputs.shape
#display(inputs.shape, inputs)
layer1 = Layer_Dense(1,5)
layer2 = Layer_Dense(5,1)
activation1 = Activation_ReLU()
activation2 = Activation_ReLU()

layer1.forward(inputs)
print(layer1.output)
activation1.forward(layer1.output)

# layer2.forward(layer1.output)
# print(layer2.output)

(99, 1)

(1, 5)

(5, 1)

[[ -0.12881418  -0.04195655   0.15460341  -0.02359112   0.12251255]
 [ -0.25762835  -0.0839131    0.30920683  -0.04718224   0.24502509]
 [ -0.38644253  -0.12586965   0.46381024  -0.07077336   0.36753764]
 [ -0.51525671  -0.1678262    0.61841366  -0.09436448   0.49005018]
 [ -0.64407088  -0.20978275   0.77301707  -0.1179556    0.61256273]
 [ -0.77288506  -0.2517393    0.92762049  -0.14154672   0.73507527]
 [ -0.90169924  -0.29369585   1.0822239   -0.16513784   0.85758782]
 [ -1.03051342  -0.33565241   1.23682732  -0.18872896   0.98010036]
 [ -1.15932759  -0.37760896   1.39143073  -0.21232008   1.10261291]
 [ -1.28814177  -0.41956551   1.54603414  -0.2359112    1.22512545]
 [ -1.41695595  -0.46152206   1.70063756  -0.25950232   1.347638  ]
 [ -1.54577012  -0.50347861   1.85524097  -0.28309344   1.47015054]
 [ -1.6745843   -0.54543516   2.00984439  -0.30668456   1.59266309]
 [ -1.80339848  -0.58739171   2.1644478   -0.33027568   1.71517563]
 [ -1.93221265  -0.62934826   2.31905122  -0.353

In [86]:
a = np.array([1,2,3])
a = a.reshape(1,3)
np.dot(a,a.T)
np.matmul(a,a.T)
a.shape

b = np.array([[1,2], [4,5], [7,8]])
b

np.dot(b,b.T)
np.matmul(b,b.T)


array([[14]])

array([[14]])

(1, 3)

array([[1, 2],
       [4, 5],
       [7, 8]])

array([[  5,  14,  23],
       [ 14,  41,  68],
       [ 23,  68, 113]])

array([[  5,  14,  23],
       [ 14,  41,  68],
       [ 23,  68, 113]])